name: dartzmq
description: A simple dart zeromq implementation/wrapper around the libzmq C++ library
version: 1.0.0-dev.9
homepage: https://github.com/enwi/dartzmq

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec